id: 4949e5159d854527878fa54cff7d263c
initial_creation_type: ocr
source_metadata:
  volumes:
    8653f9337c434492962dc8c58b4dfe25:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: དཔལ་འཁོར་ལོ་སྡོམ་པའི་སྒྲུབ་ཐབས།
      total_pages: 2107
      volume_number: 11
